language: go

go:
  - 1.8.x
  - tip

sudo: false

branches:
  only:
    - master

services:
  - redis-server

before_install:
  - redis-server /etc/redis/redis.conf --daemonize yes --port 16379 --requirepass '5RdXzAq1'

install:
  - go get -v github.com/Masterminds/glide
  - glide install

script:
 - go test -v ./app/...
