# https://docs.travis-ci.com/user/getting-started/
language: go

go:
  - tip

branches:
  only:
    - master

os:
  - linux

sudo: required

services:
  - redis-server
  - docker

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y build-essential nodejs
  - sudo redis-server /etc/redis/redis.conf --daemonize yes --port 16379 --requirepass '5RdXzAq1'
  - sudo docker pull alpine:3.5

install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - cd $TRAVIS_BUILD_DIR/ui
  - npm install --registry=https://registry.npm.taobao.org
  - cd $TRAVIS_BUILD_DIR

script:
  - make test
  - make package
