FROM alpine：3.5
MAINTAINER Zongzhi Bai <dolphineor@gmail.com>

ADD ./dist/squirrel-server /

RUN mkdir -p /var/log/squirrel
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

EXPOSE 7000

CMD ["/squirrel-server"]
