version: "3"
services:
  # http://www.troylc.cc/docker-swarm/docker/docker-compose/2017/10/27/docker-swarm-stack-compose-order.html
  web:
      build:
        context: .
      image: lavenderx/squirrel
      container_name: squirrel
      ports:
        - 7000:7000
      networks:
        - squirrel-net
      depends_on:
        - mysql
#          condition: service_healthy
        - redis
#          condition: service_started
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7000/"]
        interval: 30s
        timeout: 15s
        retries: 3

  mysql:
    image: mysql:${MYSQL_TAG}
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - squirrel-net
    restart: on-failure
    volumes:
      - /var/lib/mysql
      - ./scripts/mysql/my.cnf:/etc/my.cnf
      - ./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "TZ=Asia/Shanghai"
    healthcheck:
      test: "mysql -ufoo -ptest1234 -Dtest -e\"select version();\""
      interval: 60s
      timeout: 20s
      retries: 3

  redis:
    image: redis:${REDIS_TAG}
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - squirrel-net
    environment:
      - "TZ=Asia/Shanghai"
    restart: on-failure
    command: redis-server --requirepass 5RdX!zAq1
    healthcheck:
      test: ["CMD-SHELL", "nc -v -w 5 localhost -z 6379 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3

networks:
  squirrel-net:
