FROM alpine:3.5
MAINTAINER Zongzhi Bai <dolphineor@gmail.com>

ADD ./dist/squirrel-server /

RUN mkdir -p /var/log/squirrel
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone
RUN date

EXPOSE 7000

CMD ["/squirrel-server"]
