FROM alpine:3.5
MAINTAINER Zongzhi Bai <dolphineor@gmail.com>

ADD ./dist/squirrel-server /

RUN apk update && apk add ca-certificates && \
    apk add tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
RUN mkdir -p /var/log/squirrel

EXPOSE 7000

CMD ["/squirrel-server"]
