server:
  port: 7000

mysql:
  driver: mysql
  dataSource: foo:test1234@tcp(mysql:3306)/test?charset=utf8mb4
  showSql: false
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  address: redis:6379
  password: 5RdX!zAq1
