server:
  port: 7000

mysql:
  driver: mysql
  dataSource: kiwi:test1234$@tcp(127.0.0.1:3306)/squirrel?charset=utf8mb4
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  address: 127.0.0.1:16379
  password: 5RdXzAq1
